name: Feature request
description: Suggest an idea for Goonstation Launcher
type: Feature
body:
  - type: markdown
    attributes:
      value: |
        **Thanks for suggesting a feature!**
        Please fill out the form below.
  - type: input
    id: title
    attributes:
      label: Feature summary
      description: Briefly describe the feature
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: Description
      description: What would you like to see added or changed?
    validations:
      required: true
  - type: textarea
    id: motivation
    attributes:
      label: Motivation
      description: Why is this feature important to you or the project?
    validations:
      required: false
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives
      description: Any alternative solutions or features you've considered?
    validations:
      required: false
