name: 'CI'

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-and-test:
    permissions:
      contents: read
    strategy:
      matrix:
        platform: [windows-latest]

    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: Setup Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x
          cache: true

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Install frontend dependencies
        run: deno install

      - name: Check Deno formatting
        run: deno fmt --check

      - name: Run Deno linter
        run: deno lint

      # If tagName and releaseId are omitted tauri-action will only build the app and won't try to upload any assets.
      - name: Build Tauri app
        uses: tauri-apps/tauri-action@v0
